import json
from pathlib import Path
from panel_engine.unified_pipeline import generate_panels_unified
from page.builder import build_comic_page
from config import CONFIG
root=Path(__file__).parent; job=root/'outputs'/'curated_jobs'/'cat_cartoony'; job.mkdir(parents=True,exist_ok=True); schema=job/'story.json'
data={"characters":{"cat":{"name":"Mochi","description":"A spoiled orange cat who demands luxury but loves cardboard boxes.","base_prompt_en":"orange tabby cat, green eyes, tiny blue collar, round face, expressive eyebrows"},"owner":{"name":"Sam","description":"A tired pet owner trying to solve the cat's demands.","base_prompt_en":"young adult, short dark hair, brown eyes, yellow hoodie, round glasses"}},"pages":[{"page_number":1,"panels":[{"id":"panel_1_1","panel_prompt_en":"orange cat dramatically pointing at an expensive automatic feeder, owner listening in disbelief, cozy kitchen","panel_negative_en":"blurry, malformed, extra limbs, duplicate characters, text, watermark","active_char_ids":["cat","owner"],"character_actions":{"cat":{"action_en":"points accusingly at the feeder","pose_en":"standing proudly"},"owner":{"action_en":"holds the instruction manual","pose_en":"tired and confused"}},"dialogues":[{"character_id":"cat","text":"I paid for the premium model.","emotion":"demanding"}]},{"id":"panel_1_2","panel_prompt_en":"owner plugs in the automatic feeder, cat watches with intense suspicion, kitchen counter, silent reaction","panel_negative_en":"blurry, malformed, extra limbs, duplicate characters, text, watermark","active_char_ids":["cat","owner"],"character_actions":{"cat":{"action_en":"leans toward the feeder without touching it","pose_en":"suspicious"},"owner":{"action_en":"presses the power button","pose_en":"hopeful"}},"dialogues":[]},{"id":"panel_1_3","panel_prompt_en":"automatic feeder dispenses food, cat recoils dramatically and points at a cardboard box, owner shocked","panel_negative_en":"blurry, malformed, extra limbs, duplicate characters, text, watermark","active_char_ids":["cat","owner"],"character_actions":{"cat":{"action_en":"points at the empty cardboard box","pose_en":"offended"},"owner":{"action_en":"stares at the spilled food","pose_en":"shocked"}},"dialogues":[{"character_id":"cat","text":"That machine has no respect for presentation.","emotion":"offended"}]},{"id":"panel_1_4","panel_prompt_en":"orange cat curled happily inside a cardboard box beside the untouched automatic feeder, owner facepalming, cozy kitchen","panel_negative_en":"blurry, malformed, extra limbs, duplicate characters, text, watermark","active_char_ids":["cat","owner"],"character_actions":{"cat":{"action_en":"sleeps inside the cardboard box","pose_en":"blissful"},"owner":{"action_en":"covers their face with one hand","pose_en":"defeated"}},"dialogues":[{"character_id":"owner","text":"The box was free.","emotion":"defeated"}]}]}]}
schema.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf8')
panels=job/'panels'; generate_panels_unified(str(schema),str(panels),CONFIG.models.base_model,device='cuda',base='SDv1.5',lora_path='models/loras/cartoony.safetensors',panel_steps=80,guidance_scale=7.5,max_render_width=896,max_render_height=896,negative_prompt_extra='bad anatomy, extra limbs, duplicate, text, watermark',seed=7101,style_name=CONFIG.style.preset)
out=job/'comic_page.png'; build_comic_page(str(panels),str(out),[f'panel_1_{i}' for i in range(1,5)],str(schema),inject_bubbles=True,use_adaptive_layout=True,layout_name='Layout4Panels_Dynamic'); print(out)
